name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - Dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - Dev

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      NODE_VERSION: '18'                 # matches what Oryx used in your logs
      NPM_CONFIG_LEGACY_PEER_DEPS: 'true' # ignore peer-dep conflicts during npm install
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_ROCK_05FAC6600 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"          # React is at repo root
          api_location: ""           # backend is separate
          output_location: "build"
          # Force the exact commands so npm uses the legacy peer deps behavior:
          app_build_command: |
            node -v
            npm ci --legacy-peer-deps
            npm run build

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_ROCK_05FAC6600 }}
          action: "close"
